import SearchMethod from "@/component/SearchMethod";
export const metadata = {
  title: "Our-Doctors",
  description: "Generated by create next app",
};
const Doctors = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/doctors`, {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch doctors");
  }

  const Doctors = await res.json();

  return <SearchMethod doctors={Doctors} />;
};

export default Doctors;
