import AboutUs from "@/component/AboutUs";
import Banner from "@/component/Banner";
import Services from "@/component/Services";
import TopRated from "@/component/TopRated";
import React from "react";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
const Home = () => {
  return (
    <div>
      <Banner />
      <TopRated />
      <AboutUs />
      <Services />
    </div>
  );
};

export default Home;
