import Banner from "@/component/Banner";
import TopRated from "@/component/TopRated";
import React from "react";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
const Home = () => {
  return (
    <div>
      <Banner />
      <TopRated />
    </div>
  );
};

export default Home;
