import SearchMethod from "@/component/SearchMethod";
export const metadata = {
  title: "All-Appointment",
  description: "Generated by create next app",
};
const Doctors = async () => {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/doctors`);

  if (!res.ok) {
    throw new Error("Failed to fetch doctors");
  }

  const doctors = await res.json();
  return <SearchMethod doctors={doctors} />;
};

export default Doctors;
