import { authClient } from "@/lib/auth-client";
import {
  Button,
  FieldError,
  Input,
  Label,
  Modal,
  Surface,
  TextField,
} from "@heroui/react";
import { Pencil } from "lucide-react";
import React from "react";
import toast from "react-hot-toast";
export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};
const EditProfile = () => {
  const onsubmit = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const profileData = Object.fromEntries(formData.entries());
    // console.log(profileData);
    const { data, error } = await authClient.updateUser({
      name: profileData.name, // required
      image: profileData.image, // required
    });
    console.log(data);
    // console.log(data, error);
    if (error) {
      toast.error(error.message);
      return;
    }
    toast.success("Profile updated successfully!");
    window.location.reload();
  };
  return (
    <div className="my-20 ">
      <Modal className="">
        <Button
          size="sm"
          className={"hover:text-cyan-600 transition group font-medium"}
          variant="bordered"
        >
          Edit
        </Button>

        <Modal.Backdrop>
          <Modal.Container placement="auto">
            <Modal.Dialog className="sm:max-w-md">
              <Modal.CloseTrigger />
              <Modal.Header>
                <Modal.Icon className="bg-accent-soft text-accent-soft-foreground">
                  <Pencil className="size-5" />
                </Modal.Icon>
                <Modal.Heading>Edit Carefully</Modal.Heading>
              </Modal.Header>
              <Modal.Body className="p-6">
                <Surface variant="default">
                  <form onSubmit={onsubmit} className="p-10 space-y-8">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                      {/* Destination Name */}
                      <div className="md:col-span-2">
                        <TextField>
                          <Label>User Name</Label>

                          <Input name="name" className="rounded-2xl" />
                          <FieldError />
                        </TextField>

                        <TextField>
                          <Label>Image</Label>
                          <Input
                            name="image"
                            type="text"
                            className="rounded-2xl"
                          />
                          <FieldError />
                        </TextField>
                      </div>

                      {/* Image URL */}
                    </div>

                    <Button
                      type="submit"
                      variant="ghost"
                      className="w-full rounded-none "
                    >
                      Update Booking
                    </Button>
                  </form>
                </Surface>
              </Modal.Body>
            </Modal.Dialog>
          </Modal.Container>
        </Modal.Backdrop>
      </Modal>
    </div>
  );
};

export default EditProfile;
