import MyBooking from "@/component/MyBooking";
import Profile from "@/component/Profile";
import { Tabs } from "@heroui/react";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashBoard = async () => {
  
  return (
    <div className="container mx-auto my-20">
      <h2 className="text-center font-bold text-2xl py-2">Dashboard</h2>
      <Tabs className=" ">
        <Tabs.ListContainer>
          <Tabs.List aria-label="Options" >
            <Tabs.Tab id="analytics">
              My Booking
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="reports">
              Profile
              <Tabs.Indicator />
            </Tabs.Tab>
          </Tabs.List>
        </Tabs.ListContainer>

        <Tabs.Panel className="pt-4" id="analytics">
          <MyBooking></MyBooking>
        </Tabs.Panel>
        <Tabs.Panel className="pt-4 flex " id="reports">
          <Profile />
        </Tabs.Panel>
      </Tabs>
    </div>
  );
};

export default DashBoard;
