import MyBooking from "@/component/MyBooking";
import Profile from "@/component/Profile";
import { auth } from "@/lib/auth";
import { Tabs } from "@heroui/react";
import { headers } from "next/headers";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashBoard = async () => {
  const { token: tokenData } = await auth.api.getToken({
    headers: await headers(),
  });
  // console.log(tokenData);
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/bookings`, {
    headers: {
      authorization: `Bearer ${tokenData}`,
    },
  });
  const bookingData = await res.json();
  // console.log(bookingData);
  return (
    <div className="container mx-auto my-20">
      <h2 className="text-center font-bold text-2xl py-2">Dashboard</h2>
      <Tabs className=" ">
        <Tabs.ListContainer>
          <Tabs.List aria-label="Options" className="justify-center">
            <Tabs.Tab id="analytics">
              My Booking
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="reports">
              Profile
              <Tabs.Indicator />
            </Tabs.Tab>
          </Tabs.List>
        </Tabs.ListContainer>

        <Tabs.Panel className="pt-4" id="analytics">
          <MyBooking bookingData={bookingData}></MyBooking>
        </Tabs.Panel>
        <Tabs.Panel className="pt-4 flex " id="reports">
          <Profile />
        </Tabs.Panel>
      </Tabs>
    </div>
  );
};

export default DashBoard;
